#!/bin/bash
# Finds and converts all webm files in the current directory to mp4 format using ffmpeg.

for filename in $(find . -type f -name "*.webm")
do
    echo "Found webm file: $filename"
    newname=$(echo "$filename" | sed 's/.webm/.mp4/')
    echo "Will be converted to: $newname"
    ffmpeg -i "$filename" "$newname"
    if [ $? -eq 0 ]; then
        echo "Successfully converted $filename to $newname."
        rm "$filename"
    else
        echo "An error occurred during the conversion of $filename."
    fi
done
