#!/usr/bin/env python3
# Finds and converts all webm files in the current directory to mp4 format using ffmpeg.

import os, fnmatch
from pathlib import Path
import ffmpeg_python as ffmpeg

def find_files(directory, pattern):
    for root, dirs, files in os.walk(directory):
        for basename in files:
            if fnmatch.fnmatch(basename, pattern):
                filename = os.path.join(root, basename)
                yield filename


for filename in find_files('.', '*.webm'):
    print('Found webm file:', filename)
    newname = str(filename).replace('webm','mp4')
    print('Will be converted to:', newname)
    try:
        stream = ffmpeg.input(filename)
        stream = ffmpeg.output(stream, newname)
        ffmpeg.run(stream)
        os.remove(filename)
    except Exception as e:
        print("An error occurred during the conversion: ", str(e))
